# Generated by Django 2.2 on 2019-08-08 13:02

from django.db import migrations


def create_srs(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    SRS = apps.get_model('geo', 'SRS')

    srs2056, created = SRS.objects.get_or_create(id=2056, name="CH1903+ / LV95")
    srs3857, created = SRS.objects.get_or_create(id=3857, name="WebMercator")
    srs4326, created = SRS.objects.get_or_create(id=4326, name="WGS 84")
    srs21781, created = SRS.objects.get_or_create(id=21781, name="CH1903 / LV03")



class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_srs)
    ]
