# Generated by Django 2.2 on 2019-06-25 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
        ('layers', '0002_auto_20190509_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='tileset',
            name='publication_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publication.WMTS'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='layer_name',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='tileset',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
