# Generated by Django 2.2 on 2019-06-28 07:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import layers.models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
        ('layers', '0004_dataset_timing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tileset',
            old_name='format',
            new_name='image_type',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='timing',
            field=models.CharField(default='current', help_text='Timing can have one of \n        the following formats: \n        <pre>current | TT | TT,TT,TT | TT/TT/RES</pre>\n        where <em>TT</em> is a valid ISO 8601 timestamp (e.g. 2015-05-12T13:54:01Z), \n        and <em>RES</em> is the resolution in the form <b>P</b>[n]Y[n]M[n]D<b>T</b>[n]H[n]M[n]S \n        (e.g. P1Y). Examples\n        <pre>2008,2011,2012</pre>\n        <pre>2005-11-01T10:15Z/2019-02-15T09:30Z/PT5M</pre>\n        ', max_length=256, validators=[layers.models.validate_timing]),
        ),
        migrations.AlterField(
            model_name='tileset',
            name='publication_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publication.WMTS'),
        ),
        migrations.CreateModel(
            name='WMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('mapfile', models.TextField()),
                ('mapfile_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.Dataset')),
                ('publication_services', models.ManyToManyField(to='publication.WMS')),
            ],
        ),
    ]
