# Generated by Django 2.2 on 2019-07-10 12:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_auto_20190628_0731'),
        ('layers', '0005_auto_20190628_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapServerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('mapfile', models.TextField()),
                ('mapfile_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.Dataset')),
                ('publication_services', models.ManyToManyField(to='publication.WMS')),
            ],
        ),
        migrations.DeleteModel(
            name='WMS',
        ),
    ]
