# Generated by Django 2.2 on 2019-07-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0006_auto_20190710_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapserverconfig',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
