# Generated by Django 2.2 on 2019-08-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0009_dataset_srs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='short_description',
        ),
        migrations.AddField(
            model_name='dataset',
            name='abstract_key',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='description_key',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='short_description_key',
            field=models.SlugField(null=True),
        ),
    ]
