# Generated by Django 2.2 on 2019-08-09 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0005_auto_20190809_0925'),
        ('layers', '0011_auto_20190809_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='abstract_key',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='description_key',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='short_description_key',
        ),
        migrations.AddField(
            model_name='dataset',
            name='abstract',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_abstract', to='translation.Translation', verbose_name='abstract'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_description', to='translation.Translation', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='short_description',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_short_description', to='translation.Translation', verbose_name='short_description'),
        ),
    ]
