# Generated by Django 2.2 on 2019-08-19 11:37

from django.db import migrations, models
import layers.models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0013_auto_20190813_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='layer_name',
        ),
        migrations.AddField(
            model_name='dataset',
            name='db_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=512, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapserverlayer',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mapserverlayer',
            name='template',
            field=models.CharField(default='ttt', max_length=512),
        ),
        migrations.AddField(
            model_name='mapserverlayer',
            name='wms_extent',
            field=layers.models.ExtentField(base_field=models.IntegerField(), null=True, size=4),
        ),
    ]
