# Generated by Django 2.2 on 2019-08-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0014_auto_20190819_1137'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mapserverlayer',
            unique_together={('group', 'mapserver_layer_name')},
        ),
    ]
