# Generated by Django 2.2 on 2019-08-28 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0017_mapserverlayer_wms_enable_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tileset',
            name='published',
            field=models.BooleanField(default=False, help_text='Publication in GetCapabilities'),
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_infos', models.URLField(blank=True, null=True)),
                ('url_download', models.URLField(blank=True, null=True)),
                ('url_portal', models.URLField(blank=True, null=True)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='layers.Dataset')),
            ],
        ),
    ]
