# Generated by Django 2.2 on 2019-08-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0018_auto_20190828_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='url_download',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='url_infos',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='url_portal',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
