# Generated by Django 2.2 on 2019-06-24 14:18

from django.db import migrations, models
import translation.models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_auto_20190509_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationkey',
            name='id',
            field=models.SlugField(max_length=512, primary_key=True, serialize=False, validators=[translation.models.validate_not_none]),
        ),
    ]
