version: "3.4"
services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: dj_control
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      # POSTGRES_MULTIPLE_EXTENSIONS: postgis,postgis_topology
      # EXTRA_CONF: log_min_messages = ${DB_LOG_LEVEL:-FATAL}
    user: ${UID}
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ${PWD}/pg-data
        target: /var/lib/postgresql/data
