# Generated by Django 5.0 on 2024-01-25 16:20

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('slug', models.SlugField(default='all', max_length=128)),
                ('in_stac', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('slug', models.SlugField(default='all', max_length=128)),
                ('mf_chsdi_file', models.CharField(blank=True, max_length=256, null=True)),
                ('mf_chsdi_models', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None)),
                ('mf_chsdi_model_definitions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('used_in_feature_api', models.BooleanField(default=False)),
                ('used_in_wms_layer', models.BooleanField(default=False)),
                ('mapfile_data_string', models.CharField(blank=True, max_length=2048, null=True)),
                ('db_name', models.CharField(blank=True, max_length=256, null=True)),
                ('db_schema', models.CharField(blank=True, max_length=64, null=True)),
                ('db_table', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RasterCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('slug', models.SlugField(default='all', max_length=128)),
                ('file', models.CharField(blank=True, max_length=512, null=True)),
                ('tiled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VectorField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('text', 'text'), ('double precision', 'double precision'), ('timestamp without time zone', 'timestamp without time zone'), ('integer', 'integer'), ('character varying', 'character varying'), ('geometry', 'geometry'), ('unknown', 'unknown')], max_length=128)),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VectorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('db_fields', models.JSONField(null=True)),
                ('chsdi_fields', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VectorStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=512, unique=True)),
                ('geocat_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('db_name', models.CharField(max_length=64, null=True)),
                ('abstract', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_abstract', to='translation.translation', verbose_name='abstract')),
            ],
        ),
    ]
