# Generated by Django 5.0 on 2024-01-25 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0001_initial'),
        ('provider', '0001_initial'),
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='attribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider.attribution'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_description', to='translation.translation', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider.provider'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='short_description',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_short_description', to='translation.translation', verbose_name='short_description'),
        ),
        migrations.AddField(
            model_name='downloadcollection',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.dataset'),
        ),
        migrations.AddField(
            model_name='featurecollection',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.dataset'),
        ),
        migrations.AddField(
            model_name='rastercollection',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.dataset'),
        ),
        migrations.AddField(
            model_name='vectormodel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.provider'),
        ),
        migrations.AddField(
            model_name='vectorfield',
            name='vectormodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.vectormodel'),
        ),
        migrations.AddField(
            model_name='vectorstyle',
            name='vectormodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.vectormodel'),
        ),
        migrations.AlterUniqueTogether(
            name='downloadcollection',
            unique_together={('dataset', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='featurecollection',
            unique_together={('dataset', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='rastercollection',
            unique_together={('slug', 'file')},
        ),
    ]
