# Generated by Django 2.2 on 2019-06-24 07:16

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layers', '0002_auto_20190509_1405'),
        ('translation', '0002_auto_20190509_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staging', models.CharField(choices=[('test', 'testing environments (dev and int)'), ('prod', 'production environment')], default='test', max_length=16)),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_topic_name', to='translation.TranslationKey', verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.Dataset')),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_cataloglayer_name', to='translation.TranslationKey', verbose_name='name')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.CatalogLayer')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Topic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
