# Generated by Django 2.2 on 2019-06-24 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_auto_20190509_1223'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_topic_name', to='translation.TranslationKey', verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
