# Generated by Django 2.2 on 2019-06-24 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190624_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='cataloglayer',
            name='bodm_legacy_catalog_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_topic_title', to='translation.TranslationKey', verbose_name='title'),
        ),
    ]
