# Generated by Django 2.2 on 2019-06-25 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0003_auto_20190625_1105'),
        ('catalog', '0005_auto_20190624_1418'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cataloglayer',
            unique_together={('catalog_entry', 'dataset')},
        ),
    ]
