# Generated by Django 2.2 on 2019-08-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190625_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogentry',
            name='name',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='title',
        ),
        migrations.AddField(
            model_name='catalogentry',
            name='name_key',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='title_key',
            field=models.SlugField(null=True),
        ),
    ]
