# Generated by Django 2.2 on 2019-08-09 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0005_auto_20190809_0925'),
        ('catalog', '0007_auto_20190809_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogentry',
            name='name_key',
        ),
        migrations.AddField(
            model_name='catalogentry',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='translation.Translation'),
        ),
    ]
