# Generated by Django 2.2 on 2019-08-09 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190809_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogentry',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_cataloglayer_name', to='translation.Translation', verbose_name='name'),
        ),
    ]
