# Generated by Django 5.0 on 2024-01-25 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('prefix', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribution_name', to='translation.translation', verbose_name='name')),
                ('short', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribution_short', to='translation.translation', verbose_name='short')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.provider')),
            ],
        ),
    ]
