# Generated by Django 2.2 on 2019-06-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoJSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staging', models.CharField(choices=[('dev', 'development'), ('int', 'integration'), ('prod', 'production')], default='dev', max_length=16)),
                ('fqdn', models.CharField(default='bgdi.ch', max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staging', models.CharField(choices=[('dev', 'development'), ('int', 'integration'), ('prod', 'production')], default='dev', max_length=16)),
                ('fqdn', models.CharField(default='bgdi.ch', max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WMTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staging', models.CharField(choices=[('dev', 'development'), ('int', 'integration'), ('prod', 'production')], default='dev', max_length=16)),
                ('fqdn', models.CharField(default='bgdi.ch', max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
