# Generated by Django 5.0 on 2023-12-12 09:33

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(db_index=True, default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('key', models.SlugField(max_length=500)),
                ('revision', models.PositiveIntegerField(db_index=True, default=0)),
                ('de', models.TextField(null=True)),
                ('fr', models.TextField(null=True)),
                ('it', models.TextField(null=True)),
                ('en', models.TextField(null=True)),
                ('rm', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
                'unique_together': {('key', 'revision')},
                'index_together': {('current', 'key')},
            },
            managers=[
                ('versioned', django.db.models.manager.Manager()),
            ],
        ),
    ]
